#  menu items
[[main]]
  name = "Home"
  weight = 1
  url = "/"

[[main]]
  name = "Docs"
  weight = 2
  url = "docs/"

# [[main]]
#   name = "Example"
#   weight = 3
#   url = "https://docs.neuralvibes.com"

# [[main]]
#   name = "Blog"
#   weight = 4
#   url = "blog/"